export interface SkillSeed {
  name: string;
  slug: string;
  aliases: string[];
  category: string;
}

/** Modest Phase 2 taxonomy. Live rows are seeded from 0004; tests reuse this list. */
export const SKILL_CATALOG: readonly SkillSeed[] = [
  { name: 'JavaScript', slug: 'javascript', aliases: ['js', 'ecmascript'], category: 'language' },
  { name: 'TypeScript', slug: 'typescript', aliases: ['ts'], category: 'language' },
  { name: 'HTML', slug: 'html', aliases: ['html5'], category: 'language' },
  { name: 'CSS', slug: 'css', aliases: ['css3'], category: 'language' },
  { name: 'Java', slug: 'java', aliases: [], category: 'language' },
  { name: 'Python', slug: 'python', aliases: [], category: 'language' },
  { name: 'C#', slug: 'csharp', aliases: ['c sharp', 'csharp'], category: 'language' },
  { name: 'C++', slug: 'cpp', aliases: ['cplusplus', 'c plus plus'], category: 'language' },
  { name: 'SQL', slug: 'sql', aliases: [], category: 'language' },
  { name: 'Go', slug: 'go', aliases: ['golang'], category: 'language' },
  { name: 'Rust', slug: 'rust', aliases: [], category: 'language' },
  { name: 'PHP', slug: 'php', aliases: [], category: 'language' },
  { name: 'Ruby', slug: 'ruby', aliases: [], category: 'language' },
  { name: 'Swift', slug: 'swift', aliases: [], category: 'language' },
  { name: 'Kotlin', slug: 'kotlin', aliases: [], category: 'language' },
  { name: 'React', slug: 'react', aliases: ['react.js', 'reactjs', 'react js'], category: 'frontend' },
  { name: 'Next.js', slug: 'nextjs', aliases: ['nextjs', 'next js'], category: 'frontend' },
  { name: 'Angular', slug: 'angular', aliases: ['angularjs', 'angular.js'], category: 'frontend' },
  { name: 'Vue', slug: 'vue', aliases: ['vue.js', 'vuejs', 'vue js'], category: 'frontend' },
  { name: 'Redux', slug: 'redux', aliases: [], category: 'frontend' },
  { name: 'Redux Toolkit', slug: 'redux-toolkit', aliases: ['rtk', 'redux-toolkit'], category: 'frontend' },
  { name: 'RTK Query', slug: 'rtk-query', aliases: ['rtkquery'], category: 'frontend' },
  { name: 'Tailwind CSS', slug: 'tailwindcss', aliases: ['tailwind', 'tailwindcss'], category: 'frontend' },
  { name: 'Material UI', slug: 'material-ui', aliases: ['mui', 'material-ui', 'materialui'], category: 'frontend' },
  { name: 'shadcn/ui', slug: 'shadcn-ui', aliases: ['shadcn', 'shadcn ui'], category: 'frontend' },
  { name: 'Radix UI', slug: 'radix-ui', aliases: ['radix', 'radixui'], category: 'frontend' },
  { name: 'SCSS', slug: 'scss', aliases: ['sass'], category: 'frontend' },
  { name: 'Vite', slug: 'vite', aliases: [], category: 'frontend' },
  { name: 'Webpack', slug: 'webpack', aliases: [], category: 'frontend' },
  { name: 'React Native', slug: 'react-native', aliases: ['reactnative', 'react-native'], category: 'mobile' },
  { name: 'Expo', slug: 'expo', aliases: [], category: 'mobile' },
  { name: 'Flutter', slug: 'flutter', aliases: [], category: 'mobile' },
  { name: 'Android', slug: 'android', aliases: [], category: 'mobile' },
  { name: 'iOS', slug: 'ios', aliases: [], category: 'mobile' },
  { name: 'Node.js', slug: 'nodejs', aliases: ['node', 'nodejs', 'node js'], category: 'backend' },
  { name: 'Express', slug: 'express', aliases: ['express.js', 'expressjs'], category: 'backend' },
  { name: 'NestJS', slug: 'nestjs', aliases: ['nest.js', 'nest'], category: 'backend' },
  { name: 'REST API', slug: 'rest-api', aliases: ['rest', 'restful', 'rest apis'], category: 'backend' },
  { name: 'GraphQL', slug: 'graphql', aliases: [], category: 'backend' },
  { name: 'WebSocket', slug: 'websocket', aliases: ['websockets'], category: 'backend' },
  { name: 'PostgreSQL', slug: 'postgresql', aliases: ['postgres', 'psql'], category: 'database' },
  { name: 'MongoDB', slug: 'mongodb', aliases: ['mongo'], category: 'database' },
  { name: 'Redis', slug: 'redis', aliases: [], category: 'database' },
  { name: 'Supabase', slug: 'supabase', aliases: [], category: 'database' },
  { name: 'Firebase', slug: 'firebase', aliases: [], category: 'database' },
  { name: 'MySQL', slug: 'mysql', aliases: [], category: 'database' },
  { name: 'Prisma', slug: 'prisma', aliases: [], category: 'database' },
  { name: 'AWS', slug: 'aws', aliases: ['amazon web services'], category: 'cloud' },
  { name: 'Azure', slug: 'azure', aliases: ['microsoft azure'], category: 'cloud' },
  { name: 'GCP', slug: 'gcp', aliases: ['google cloud', 'google cloud platform'], category: 'cloud' },
  { name: 'Docker', slug: 'docker', aliases: [], category: 'cloud' },
  { name: 'Kubernetes', slug: 'kubernetes', aliases: ['k8s'], category: 'cloud' },
  { name: 'CI/CD', slug: 'ci-cd', aliases: ['cicd', 'continuous integration'], category: 'cloud' },
  { name: 'GitHub Actions', slug: 'github-actions', aliases: ['gh actions'], category: 'cloud' },
  { name: 'Terraform', slug: 'terraform', aliases: [], category: 'cloud' },
  { name: 'Linux', slug: 'linux', aliases: [], category: 'cloud' },
  { name: 'Git', slug: 'git', aliases: [], category: 'cloud' },
  { name: 'Jest', slug: 'jest', aliases: [], category: 'testing' },
  { name: 'Vitest', slug: 'vitest', aliases: [], category: 'testing' },
  { name: 'Playwright', slug: 'playwright', aliases: [], category: 'testing' },
  { name: 'Cypress', slug: 'cypress', aliases: [], category: 'testing' },
  { name: 'React Testing Library', slug: 'react-testing-library', aliases: ['rtl', 'testing-library'], category: 'testing' },
  { name: 'Accessibility', slug: 'accessibility', aliases: ['a11y'], category: 'web' },
  { name: 'WCAG', slug: 'wcag', aliases: [], category: 'web' },
  { name: 'SEO', slug: 'seo', aliases: [], category: 'web' },
  { name: 'Motion', slug: 'motion', aliases: ['framer motion', 'framer-motion', 'motion/react'], category: 'web' },
  { name: 'GSAP', slug: 'gsap', aliases: ['greensock'], category: 'web' },
  { name: 'Three.js', slug: 'threejs', aliases: ['threejs', 'three js'], category: 'web' },
  { name: 'Mapbox', slug: 'mapbox', aliases: [], category: 'web' },
  { name: '.NET', slug: 'dotnet', aliases: ['dotnet', 'dot net', 'asp.net'], category: 'backend' },
  { name: 'Figma', slug: 'figma', aliases: [], category: 'web' },
  { name: 'Storybook', slug: 'storybook', aliases: [], category: 'frontend' },
  { name: 'ESLint', slug: 'eslint', aliases: [], category: 'frontend' },
  { name: 'pnpm', slug: 'pnpm', aliases: [], category: 'cloud' },
  { name: 'Vercel', slug: 'vercel', aliases: [], category: 'cloud' },
];
